### ISSUE TITLE
nodejs breakage

### ISSUE THREAD

**Issue by elijah** [felixnext/docker-speedtest#1]
This was working for a while on one of my hosts, but has recently broken:

```
npm info lifecycle speed-ui@0.1.0~start: speed-ui@0.1.0

> speed-ui@0.1.0 start /app
> node app.js

/app/models/speed.js:11
      if(line.length > 0) {
             ^

TypeError: Cannot read property 'length' of undefined
    at /app/models/speed.js:11:14
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)

npm info lifecycle speed-ui@0.1.0~start: Failed to exec start script
```

**Comment by elijah** [comment]
And here's the npm-debug.log from the container, in case it helps - I don't see anything obvious in here, but... maybe your eyes do.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle speed-ui@0.1.0~prestart: speed-ui@0.1.0
6 silly lifecycle speed-ui@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle speed-ui@0.1.0~start: speed-ui@0.1.0
8 verbose lifecycle speed-ui@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle speed-ui@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle speed-ui@0.1.0~start: CWD: /app
11 silly lifecycle speed-ui@0.1.0~start: Args: [ '-c', 'node app.js' ]
12 silly lifecycle speed-ui@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle speed-ui@0.1.0~start: Failed to exec start script
14 verbose stack Error: speed-ui@0.1.0 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid speed-ui@0.1.0
16 verbose cwd /app
17 error Linux 4.4.0-31-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.7.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error speed-ui@0.1.0 start: `node app.js`
22 error Exit status 1
23 error Failed at the speed-ui@0.1.0 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the speed-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs speed-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls speed-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by felixnext** [comment]
I added a small fix. Can you confirm if it works?

**Comment by elijah** [comment]
Yes, that seems to have fixed it.  Testing a bit more thoroughly now -- and
I forked your repo temporarily in order to spin another build up on
dockerhub.

[I have this whole thing provisioned by a chef pipeline... a few extra
steps but when the repos are good, it Just Works...]

best,

--e

**Comment by felixnext** [comment]
Then I will consider the issue closed and push an updated version to dockerhub soon.

**Comment by elijah** [comment]
Yes, it works very well again.  Thank you for your efforts on this -- it's
one of the most useful containers running in my homelab, particularly as we
watch our (Charter) cable modem's signal strength ebb in and out.  ;-)

[It's also super attractive and nice to look at :) ]

best,

--e
